// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/miniCart/getlistCEP.ts";
import * as $$$$$$$$$1 from "./actions/miniCart/removeCEP.ts";
import * as $$$$$$$$$2 from "./actions/newsletter/sendForm.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$8 from "./loaders/availableIcons.ts";
import * as $$$9 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/BannerCollection.tsx";
import * as $$$1 from "./loaders/Layouts/MaterialProduct.tsx";
import * as $$$2 from "./loaders/Layouts/MiniProductCard.tsx";
import * as $$$3 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$4 from "./loaders/Layouts/RockProduct.tsx";
import * as $$$5 from "./loaders/List/Sections.tsx";
import * as $$$6 from "./loaders/Product/SimilarProduct.ts";
import * as $$$7 from "./loaders/SearchStore.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Cards/DashCard.tsx";
import * as $$$$$$2 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$3 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$4 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$5 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$6 from "./sections/Cards/VerticalCardsGrid.tsx";
import * as $$$$$$11 from "./sections/Category/btnTeste.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$10 from "./sections/Category/CategoryListWithAnchor.tsx";
import * as $$$$$$12 from "./sections/Content/Benefits.tsx";
import * as $$$$$$13 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$14 from "./sections/Content/CallOfQuiz.tsx";
import * as $$$$$$15 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$16 from "./sections/Content/Faq.tsx";
import * as $$$$$$17 from "./sections/Content/Features.tsx";
import * as $$$$$$18 from "./sections/Content/Hero.tsx";
import * as $$$$$$19 from "./sections/Content/HeroBanner.tsx";
import * as $$$$$$20 from "./sections/Content/HeroTextWithImage.tsx";
import * as $$$$$$21 from "./sections/Content/ImageAndGrid.tsx";
import * as $$$$$$22 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$23 from "./sections/Content/ImageWithContent.tsx";
import * as $$$$$$24 from "./sections/Content/Intro.tsx";
import * as $$$$$$25 from "./sections/Content/Logos.tsx";
import * as $$$$$$26 from "./sections/Content/Partners.tsx";
import * as $$$$$$27 from "./sections/Content/RichText.tsx";
import * as $$$$$$28 from "./sections/Content/SearchContent.tsx";
import * as $$$$$$29 from "./sections/Content/StoresInfo.tsx";
import * as $$$$$$30 from "./sections/Content/Table.tsx";
import * as $$$$$$31 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$32 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$33 from "./sections/Content/TextWithImageCollection.tsx";
import * as $$$$$$34 from "./sections/Footer/Footer.tsx";
import * as $$$$$$35 from "./sections/Gallery.tsx";
import * as $$$$$$36 from "./sections/Header/Header.tsx";
import * as $$$$$$37 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$38 from "./sections/Images/BannerWithImage.tsx";
import * as $$$$$$39 from "./sections/Images/Carousel.tsx";
import * as $$$$$$40 from "./sections/Images/ComercialBanner.tsx";
import * as $$$$$$41 from "./sections/Images/DuoOfImagesAndText.tsx";
import * as $$$$$$42 from "./sections/Images/ImageDuo.tsx";
import * as $$$$$$43 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$44 from "./sections/Images/ImageQuad.tsx";
import * as $$$$$$45 from "./sections/Images/ListBanners.tsx";
import * as $$$$$$46 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$47 from "./sections/Images/StoresCarousel.tsx";
import * as $$$$$$48 from "./sections/Images/TrioOfImages.tsx";
import * as $$$$$$49 from "./sections/Images/TrioOfImagesAndProducts.tsx";
import * as $$$$$$50 from "./sections/Instagram/ListPosts.tsx";
import * as $$$$$$51 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$52 from "./sections/Links/ListLinks.tsx";
import * as $$$$$$53 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$54 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$55 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$56 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$80 from "./sections/newsletter-popup/NewsletterPopup.tsx";
import * as $$$$$$57 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$58 from "./sections/Pinterest/CodeValidation.tsx";
import * as $$$$$$59 from "./sections/Product/BannerProductDotInfo.tsx";
import * as $$$$$$60 from "./sections/Product/ImageAndModel.tsx";
import * as $$$$$$61 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$62 from "./sections/Product/NotFound.tsx";
import * as $$$$$$63 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$64 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$65 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$66 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$67 from "./sections/Product/ProductShelfWithDotsBottom.tsx";
import * as $$$$$$68 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$69 from "./sections/Product/SearchResultTeste.tsx";
import * as $$$$$$70 from "./sections/Product/ShelfCollection.tsx";
import * as $$$$$$71 from "./sections/Product/ShelfWithBanner.tsx";
import * as $$$$$$72 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$73 from "./sections/Product/Showcases.tsx";
import * as $$$$$$74 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$75 from "./sections/SEO/TextSEOCategory.tsx";
import * as $$$$$$76 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$77 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$78 from "./sections/Theme/Theme.tsx";
import * as $$$$$$79 from "./sections/Video/FullVideo.tsx";

const manifest = {
  "loaders": {
    "deco-sites/montecarlo/loaders/availableIcons.ts": $$$8,
    "deco-sites/montecarlo/loaders/icons.ts": $$$9,
    "deco-sites/montecarlo/loaders/Layouts/BannerCollection.tsx": $$$0,
    "deco-sites/montecarlo/loaders/Layouts/MaterialProduct.tsx": $$$1,
    "deco-sites/montecarlo/loaders/Layouts/MiniProductCard.tsx": $$$2,
    "deco-sites/montecarlo/loaders/Layouts/ProductCard.tsx": $$$3,
    "deco-sites/montecarlo/loaders/Layouts/RockProduct.tsx": $$$4,
    "deco-sites/montecarlo/loaders/List/Sections.tsx": $$$5,
    "deco-sites/montecarlo/loaders/Product/SimilarProduct.ts": $$$6,
    "deco-sites/montecarlo/loaders/SearchStore.ts": $$$7,
  },
  "sections": {
    "deco-sites/montecarlo/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/montecarlo/sections/Cards/DashCard.tsx": $$$$$$1,
    "deco-sites/montecarlo/sections/Cards/IconCardsCarousel.tsx": $$$$$$2,
    "deco-sites/montecarlo/sections/Cards/IconCardsCarouselWithImage.tsx":
      $$$$$$3,
    "deco-sites/montecarlo/sections/Cards/ImageCardsCarousel.tsx": $$$$$$4,
    "deco-sites/montecarlo/sections/Cards/ImageCardsCarouselWithImage.tsx":
      $$$$$$5,
    "deco-sites/montecarlo/sections/Cards/VerticalCardsGrid.tsx": $$$$$$6,
    "deco-sites/montecarlo/sections/Category/btnTeste.tsx": $$$$$$11,
    "deco-sites/montecarlo/sections/Category/CategoryBanner.tsx": $$$$$$7,
    "deco-sites/montecarlo/sections/Category/CategoryGrid.tsx": $$$$$$8,
    "deco-sites/montecarlo/sections/Category/CategoryList.tsx": $$$$$$9,
    "deco-sites/montecarlo/sections/Category/CategoryListWithAnchor.tsx":
      $$$$$$10,
    "deco-sites/montecarlo/sections/Content/Benefits.tsx": $$$$$$12,
    "deco-sites/montecarlo/sections/Content/BlogPosts.tsx": $$$$$$13,
    "deco-sites/montecarlo/sections/Content/CallOfQuiz.tsx": $$$$$$14,
    "deco-sites/montecarlo/sections/Content/CallToAction.tsx": $$$$$$15,
    "deco-sites/montecarlo/sections/Content/Faq.tsx": $$$$$$16,
    "deco-sites/montecarlo/sections/Content/Features.tsx": $$$$$$17,
    "deco-sites/montecarlo/sections/Content/Hero.tsx": $$$$$$18,
    "deco-sites/montecarlo/sections/Content/HeroBanner.tsx": $$$$$$19,
    "deco-sites/montecarlo/sections/Content/HeroTextWithImage.tsx": $$$$$$20,
    "deco-sites/montecarlo/sections/Content/ImageAndGrid.tsx": $$$$$$21,
    "deco-sites/montecarlo/sections/Content/ImageSection.tsx": $$$$$$22,
    "deco-sites/montecarlo/sections/Content/ImageWithContent.tsx": $$$$$$23,
    "deco-sites/montecarlo/sections/Content/Intro.tsx": $$$$$$24,
    "deco-sites/montecarlo/sections/Content/Logos.tsx": $$$$$$25,
    "deco-sites/montecarlo/sections/Content/Partners.tsx": $$$$$$26,
    "deco-sites/montecarlo/sections/Content/RichText.tsx": $$$$$$27,
    "deco-sites/montecarlo/sections/Content/SearchContent.tsx": $$$$$$28,
    "deco-sites/montecarlo/sections/Content/StoresInfo.tsx": $$$$$$29,
    "deco-sites/montecarlo/sections/Content/Table.tsx": $$$$$$30,
    "deco-sites/montecarlo/sections/Content/Testimonials.tsx": $$$$$$31,
    "deco-sites/montecarlo/sections/Content/TextWithImage.tsx": $$$$$$32,
    "deco-sites/montecarlo/sections/Content/TextWithImageCollection.tsx":
      $$$$$$33,
    "deco-sites/montecarlo/sections/Footer/Footer.tsx": $$$$$$34,
    "deco-sites/montecarlo/sections/Gallery.tsx": $$$$$$35,
    "deco-sites/montecarlo/sections/Header/Header.tsx": $$$$$$36,
    "deco-sites/montecarlo/sections/Images/BannerGrid.tsx": $$$$$$37,
    "deco-sites/montecarlo/sections/Images/BannerWithImage.tsx": $$$$$$38,
    "deco-sites/montecarlo/sections/Images/Carousel.tsx": $$$$$$39,
    "deco-sites/montecarlo/sections/Images/ComercialBanner.tsx": $$$$$$40,
    "deco-sites/montecarlo/sections/Images/DuoOfImagesAndText.tsx": $$$$$$41,
    "deco-sites/montecarlo/sections/Images/ImageDuo.tsx": $$$$$$42,
    "deco-sites/montecarlo/sections/Images/ImageGallery.tsx": $$$$$$43,
    "deco-sites/montecarlo/sections/Images/ImageQuad.tsx": $$$$$$44,
    "deco-sites/montecarlo/sections/Images/ListBanners.tsx": $$$$$$45,
    "deco-sites/montecarlo/sections/Images/ShoppableBanner.tsx": $$$$$$46,
    "deco-sites/montecarlo/sections/Images/StoresCarousel.tsx": $$$$$$47,
    "deco-sites/montecarlo/sections/Images/TrioOfImages.tsx": $$$$$$48,
    "deco-sites/montecarlo/sections/Images/TrioOfImagesAndProducts.tsx":
      $$$$$$49,
    "deco-sites/montecarlo/sections/Instagram/ListPosts.tsx": $$$$$$50,
    "deco-sites/montecarlo/sections/Links/LinkTree.tsx": $$$$$$51,
    "deco-sites/montecarlo/sections/Links/ListLinks.tsx": $$$$$$52,
    "deco-sites/montecarlo/sections/Links/Shortcuts.tsx": $$$$$$53,
    "deco-sites/montecarlo/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$54,
    "deco-sites/montecarlo/sections/Miscellaneous/CookieConsent.tsx": $$$$$$55,
    "deco-sites/montecarlo/sections/Miscellaneous/Slide.tsx": $$$$$$56,
    "deco-sites/montecarlo/sections/newsletter-popup/NewsletterPopup.tsx":
      $$$$$$80,
    "deco-sites/montecarlo/sections/Newsletter/Newsletter.tsx": $$$$$$57,
    "deco-sites/montecarlo/sections/Pinterest/CodeValidation.tsx": $$$$$$58,
    "deco-sites/montecarlo/sections/Product/BannerProductDotInfo.tsx": $$$$$$59,
    "deco-sites/montecarlo/sections/Product/ImageAndModel.tsx": $$$$$$60,
    "deco-sites/montecarlo/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$61,
    "deco-sites/montecarlo/sections/Product/NotFound.tsx": $$$$$$62,
    "deco-sites/montecarlo/sections/Product/NotFoundChallenge.tsx": $$$$$$63,
    "deco-sites/montecarlo/sections/Product/ProductDetails.tsx": $$$$$$64,
    "deco-sites/montecarlo/sections/Product/ProductShelf.tsx": $$$$$$65,
    "deco-sites/montecarlo/sections/Product/ProductShelfTabbed.tsx": $$$$$$66,
    "deco-sites/montecarlo/sections/Product/ProductShelfWithDotsBottom.tsx":
      $$$$$$67,
    "deco-sites/montecarlo/sections/Product/SearchResult.tsx": $$$$$$68,
    "deco-sites/montecarlo/sections/Product/SearchResultTeste.tsx": $$$$$$69,
    "deco-sites/montecarlo/sections/Product/ShelfCollection.tsx": $$$$$$70,
    "deco-sites/montecarlo/sections/Product/ShelfWithBanner.tsx": $$$$$$71,
    "deco-sites/montecarlo/sections/Product/ShelfWithImage.tsx": $$$$$$72,
    "deco-sites/montecarlo/sections/Product/Showcases.tsx": $$$$$$73,
    "deco-sites/montecarlo/sections/Product/Wishlist.tsx": $$$$$$74,
    "deco-sites/montecarlo/sections/SEO/TextSEOCategory.tsx": $$$$$$75,
    "deco-sites/montecarlo/sections/Social/InstagramPosts.tsx": $$$$$$76,
    "deco-sites/montecarlo/sections/Social/WhatsApp.tsx": $$$$$$77,
    "deco-sites/montecarlo/sections/Theme/Theme.tsx": $$$$$$78,
    "deco-sites/montecarlo/sections/Video/FullVideo.tsx": $$$$$$79,
  },
  "actions": {
    "deco-sites/montecarlo/actions/miniCart/getlistCEP.ts": $$$$$$$$$0,
    "deco-sites/montecarlo/actions/miniCart/removeCEP.ts": $$$$$$$$$1,
    "deco-sites/montecarlo/actions/newsletter/sendForm.ts": $$$$$$$$$2,
  },
  "apps": {
    "deco-sites/montecarlo/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/montecarlo/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/montecarlo",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
